<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Flávia da Fonseca Feitosa">
<meta name="author" content="Beatriz Milz">

<title>8&nbsp; Prática - Regressão Espacial – Análise de dados para o Planejamento Territorial</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../apendices/00_erros_frequentes.html" rel="next">
<link href="../praticas/07_regressao-linear.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-5fd9db47a040b21ac2cac9a0b3b722ba.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../praticas/08_regressao-espacial.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Prática - Regressão Espacial</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Procurar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Análise de dados para o Planejamento Territorial</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/beatrizmilz/ESHT011-21-analise-dados-planejamento-territorial" title="Código fonte" class="quarto-navigation-tool px-1" aria-label="Código fonte"><i class="bi bi-github"></i></a>
    <a href="../analise-de-dados-para-planejamento-territorial.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Procurar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introdução</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../praticas/01_intro_r_rstudio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introdução ao R e RStudio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../praticas/02_conceitos-basicos-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Conceitos básicos do R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../praticas/03_analise-exploratoria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Análise exploratória de dados - Parte 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../praticas/04_analise-exploratoria-ii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Análise exploratória de dados - Parte 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../praticas/05_intervalo-de-confianca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Prática - Intervalo de confiança</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../praticas/06_correlacao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Prática - Correlação</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../praticas/07_regressao-linear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Regressão Linear</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../praticas/08_regressao-espacial.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Prática - Regressão Espacial</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Apêndices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../apendices/00_erros_frequentes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Erros e <em>warnings</em> frequentes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../apendices/00_sugestao-videos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Sugestão de vídeos, posts, e outros materiais</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#introdução" id="toc-introdução" class="nav-link active" data-scroll-target="#introdução"><span class="header-section-number">8.1</span> Introdução</a></li>
  <li><a href="#carregando-os-pacotes" id="toc-carregando-os-pacotes" class="nav-link" data-scroll-target="#carregando-os-pacotes"><span class="header-section-number">8.2</span> Carregando os pacotes</a></li>
  <li><a href="#importando-os-dados" id="toc-importando-os-dados" class="nav-link" data-scroll-target="#importando-os-dados"><span class="header-section-number">8.3</span> Importando os dados</a></li>
  <li><a href="#explorando-os-dados" id="toc-explorando-os-dados" class="nav-link" data-scroll-target="#explorando-os-dados"><span class="header-section-number">8.4</span> Explorando os dados</a></li>
  <li><a href="#modelos-de-regressão-espacial-global-spatial-lag-e-spatial-error" id="toc-modelos-de-regressão-espacial-global-spatial-lag-e-spatial-error" class="nav-link" data-scroll-target="#modelos-de-regressão-espacial-global-spatial-lag-e-spatial-error"><span class="header-section-number">8.5</span> Modelos de regressão espacial global (Spatial Lag e Spatial Error)</a>
  <ul class="collapse">
  <li><a href="#preparando-os-dados" id="toc-preparando-os-dados" class="nav-link" data-scroll-target="#preparando-os-dados"><span class="header-section-number">8.5.1</span> Preparando os dados</a></li>
  <li><a href="#spatial-autoregressive-model-spatial-lagsar" id="toc-spatial-autoregressive-model-spatial-lagsar" class="nav-link" data-scroll-target="#spatial-autoregressive-model-spatial-lagsar"><span class="header-section-number">8.5.2</span> Spatial Autoregressive Model (Spatial Lag/SAR)</a></li>
  <li><a href="#conditional-autoregressive-model-spatial-errorcar" id="toc-conditional-autoregressive-model-spatial-errorcar" class="nav-link" data-scroll-target="#conditional-autoregressive-model-spatial-errorcar"><span class="header-section-number">8.5.3</span> Conditional Autoregressive Model (Spatial Error/CAR)</a></li>
  <li><a href="#exportando-os-resíduos-do-modelo" id="toc-exportando-os-resíduos-do-modelo" class="nav-link" data-scroll-target="#exportando-os-resíduos-do-modelo"><span class="header-section-number">8.5.4</span> Exportando os resíduos do modelo</a></li>
  </ul></li>
  <li><a href="#modelo-de-regressão-espacial-local-gwr" id="toc-modelo-de-regressão-espacial-local-gwr" class="nav-link" data-scroll-target="#modelo-de-regressão-espacial-local-gwr"><span class="header-section-number">8.6</span> Modelo de regressão espacial local (GWR)</a></li>
  <li><a href="#sugestões-de-materiais" id="toc-sugestões-de-materiais" class="nav-link" data-scroll-target="#sugestões-de-materiais"><span class="header-section-number">8.7</span> Sugestões de materiais</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/beatrizmilz/ESHT011-21-analise-dados-planejamento-territorial/edit/main/praticas/08_regressao-espacial.qmd" class="toc-action"><i class="bi bi-github"></i>Editar essa página</a></li><li><a href="https://github.com/beatrizmilz/ESHT011-21-analise-dados-planejamento-territorial/issues/new" class="toc-action"><i class="bi empty"></i>Criar uma issue</a></li><li><a href="https://github.com/beatrizmilz/ESHT011-21-analise-dados-planejamento-territorial/blob/main/praticas/08_regressao-espacial.qmd" class="toc-action"><i class="bi empty"></i>Ver o código fonte</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Prática - Regressão Espacial</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Docentes</div>
    <div class="quarto-title-meta-contents">
             <p><a href="https://sig.ufabc.edu.br/sigaa/public/docente/portal.jsf?siape=2064223">Flávia da Fonseca Feitosa</a> <a href="mailto:flavia.feitosa@ufabc.edu.br" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
             <p><a href="https://www.beamilz.com/">Beatriz Milz</a> <a href="mailto:milz.bea@gmail.com" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>Essa prática foi adaptada do roteiro criado por <a href="luisfelipebr.github.io/mti2020/roteiros/roteiro7.html">Luis Felipe Bortolatto da Cunha</a> para edições passadas dessa disciplina.</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Download do arquivo <code>.qmd</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Sugestão: abra o projeto no RStudio (que está usando ao longo do curso), e faça o download deste arquivo (em formato <code>.qmd</code>) com o código abaixo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">url =</span> <span class="st">"https://raw.githubusercontent.com/beatrizmilz/ESHT011-21-analise-dados-planejamento-territorial/refs/heads/main/praticas/08_regressa-espacial.qmd"</span>,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">destfile =</span> <span class="st">"08_regressa-espacial.qmd"</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<section id="introdução" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="introdução"><span class="header-section-number">8.1</span> Introdução</h2>
<p>Este roteiro tem como objetivo auxiliar na execução de <strong>modelos de regressão espacial</strong> (Spatial Lag, Spatial Error e GWR) com o software R.</p>
<p>Para executar os modelos de regressão espacial vamos utilizar dados demográficos e de consumo de água de 2010, para uma amostra de 4.417 municípios, extraídos do Censo Demográfico (IBGE) e do Sistema Nacional de Informações sobre Saneamento (SNIS), conforme análise apresentada por <a href="https://abrh.s3.sa-east-1.amazonaws.com/Sumarios/155/ea6a64ffc76c211d6b7749ab8444b626_bf87b0b219dd784ffa049f367598e626.pdf">Carmo et al., 2013</a>.</p>
<p>A base de dados está disponível para download no endereço abaixo:</p>
<p><a href="https://1drv.ms/u/s!AjettDH-3Gbni9kP8cPtA04EBQQ7xQ?e=4dyWz5" class="uri">https://1drv.ms/u/s!AjettDH-3Gbni9kP8cPtA04EBQQ7xQ?e=4dyWz5</a></p>
</section>
<section id="carregando-os-pacotes" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="carregando-os-pacotes"><span class="header-section-number">8.2</span> Carregando os pacotes</h2>
<p>Os pacotes necessários para essa prática são:</p>
<ul>
<li><p><code>tidyverse</code>: para manipulação e visualização de dados;</p></li>
<li><p><code>sf</code>: para trabalhar com dados geoespaciais vetoriais (shapefile ou geopackage)</p></li>
<li><p><code>spdep</code>: para calcular a autorrelação espacial e a matriz de pesos espaciais</p></li>
<li><p><code>spatialreg</code>: para calcular os modelos de regressão espacial global</p></li>
<li><p><code>spgrw</code>: para calcular o modelo de regressão espacial local</p></li>
</ul>
<p>Podemos instalar os pacotes:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"tidyverse"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"sf"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"spdep"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"spatialreg"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"spgwr"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Aviso
</div>
</div>
<div class="callout-body-container callout-body">
<p>Atenção: dependendo da versão de R que você está usando, você pode precisar instalar o pacote <code>Rcpp</code> antes dos pacotes de análise espacial. Se você encontrar um erro na instalação dos pacotes acima, instale o pacote citado e tente novamente. Se o problema persistir, por favor entre em contato com a equipe responsável pela disciplina.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"Rcpp"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<p>E então carregá-los:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spdep)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spatialreg)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spgwr)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="importando-os-dados" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="importando-os-dados"><span class="header-section-number">8.3</span> Importando os dados</h2>
<p>Para facilitar o download, você pode usar o código abaixo, que cria uma pasta chamada “dados” e baixa o arquivo geopackage para essa pasta. O arquivo será salvo com o nome <code>agua_rede_sf.gpkg</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Criando a pasta para armazenar os dados</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>fs<span class="sc">::</span><span class="fu">dir_create</span>(<span class="st">"dados"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Download do arquivo geopackage</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(<span class="st">"https://github.com/beatrizmilz/ESHT011-21-analise-dados-planejamento-territorial/raw/refs/heads/main/praticas/dados/agua_rede_sf.gpkg"</span>, </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">destfile =</span> <span class="st">"dados/agua_rede_sf.gpkg"</span>, </span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">mode =</span> <span class="st">"wb"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>A base de dados está em formato geopackage (.gpkg) e pode ser importada com a função <code>read_sf()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>agua_rede_sf <span class="ot">&lt;-</span> <span class="fu">read_sf</span>(<span class="st">"dados/agua_rede_sf.gpkg"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="explorando-os-dados" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="explorando-os-dados"><span class="header-section-number">8.4</span> Explorando os dados</h2>
<p>Os arquivos geoespaciais que trabalharemos são chamados de simple features (sf) no R. A sua estrutura é semelhante à de uma tabela, mas trazendo informações do Sistema de Referência de Coordenadas (CRS) e uma variável adicional: a geometria (geom ou geometry), com as coordenadas que permitem mapear os pontos, linhas ou polígonos.</p>
<p>Executando o nome do objeto é possível obter algumas dessas informações.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>agua_rede_sf</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 5567 features and 25 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -73.99045 ymin: -33.75208 xmax: -28.83609 ymax: 5.271841
Geodetic CRS:  SIRGAS 2000
# A tibble: 5,567 × 26
   ID_IBGE DOMICIL  REDE PROPREDE ID_SNIS NOME_MUN UF    REGIAO    PIB RENDAPITA
     &lt;dbl&gt;   &lt;int&gt; &lt;int&gt;    &lt;dbl&gt;   &lt;int&gt; &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt;     &lt;dbl&gt;
 1 1100015    7270  1774    0.244  110001 Alta Fl… RO    Norte  1.67e5      468.
 2 1100023   27166  9576    0.352  110002 Ariquem… RO    Norte  6.13e5      673.
 3 1100031    1975   474    0.24   110003 Cabixi   RO    Norte  4.17e4      447.
 4 1100049   24215 18428    0.761  110004 Cacoal   RO    Norte  5.83e5      719.
 5 1100056    5348  1816    0.340  110005 Cerejei… RO    Norte  8.69e4      553.
 6 1100064    5959  3617    0.607  110006 Colorad… RO    Norte  1.09e5      508.
 7 1100072    2649   344    0.130  110007 Corumbi… RO    Norte  5.84e4      402.
 8 1100080    3696   609    0.165  110008 Costa M… RO    Norte  4.97e4      353.
 9 1100098    8683  2385    0.275  110009 Espig&lt;e… RO    Norte  1.53e5      572.
10 1100106   10684  4780    0.447  110010 Guajar&lt;… RO    Norte  2.35e5      476.
# ℹ 5,557 more rows
# ℹ 16 more variables: GINI &lt;dbl&gt;, IDH &lt;dbl&gt;, IDH_CLASS &lt;chr&gt;, GE012 &lt;int&gt;,
#   AG001 &lt;int&gt;, AG020 &lt;dbl&gt;, AG022 &lt;int&gt;, CONSUMO1 &lt;dbl&gt;, CONSUMO2 &lt;dbl&gt;,
#   .fitted &lt;dbl&gt;, .resid &lt;dbl&gt;, .std.resid &lt;dbl&gt;, .hat &lt;dbl&gt;, .sigma &lt;dbl&gt;,
#   .cooksd &lt;dbl&gt;, geom &lt;MULTIPOLYGON [°]&gt;</code></pre>
</div>
</div>
<p>A função <code>names()</code> exibe os nomes das variáveis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(agua_rede_sf)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "ID_IBGE"    "DOMICIL"    "REDE"       "PROPREDE"   "ID_SNIS"   
 [6] "NOME_MUN"   "UF"         "REGIAO"     "PIB"        "RENDAPITA" 
[11] "GINI"       "IDH"        "IDH_CLASS"  "GE012"      "AG001"     
[16] "AG020"      "AG022"      "CONSUMO1"   "CONSUMO2"   ".fitted"   
[21] ".resid"     ".std.resid" ".hat"       ".sigma"     ".cooksd"   
[26] "geom"      </code></pre>
</div>
</div>
<p>Os nomes das variáveis estão codificados, apresentando correspondência às variáveis descritas abaixo:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 77%">
</colgroup>
<thead>
<tr class="header">
<th>Código</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ID_IBGE</td>
<td>Código IBGE (7 dígitos)</td>
</tr>
<tr class="even">
<td>DOMICIL</td>
<td>Quantidade de Domicílios</td>
</tr>
<tr class="odd">
<td>REDE</td>
<td>Quantidade de Domicílios com Acesso à Rede Geral de Água</td>
</tr>
<tr class="even">
<td>PROPREDE</td>
<td>Proporção de Domicílios com com Acesso à Rede Geral de Água (REDE/DOMICIL)</td>
</tr>
<tr class="odd">
<td>ID_SNIS</td>
<td>Código IBGE (6 dígitos)</td>
</tr>
<tr class="even">
<td>NOME_MUN</td>
<td>Nome do Município</td>
</tr>
<tr class="odd">
<td>UF</td>
<td>Unidade da Federação</td>
</tr>
<tr class="even">
<td>REGIAO</td>
<td>Região do País</td>
</tr>
<tr class="odd">
<td>PIB</td>
<td>Produto Interno Bruto 2010</td>
</tr>
<tr class="even">
<td>RENDAPITA</td>
<td>Renda per Capita 2010</td>
</tr>
<tr class="odd">
<td>GINI</td>
<td>Índice GINI 2010</td>
</tr>
<tr class="even">
<td>IDH</td>
<td>Índice de Desenvolvimento Humano 2010</td>
</tr>
<tr class="odd">
<td>IDH_CLASS</td>
<td>Classificação do Índice de Desenvolvimento Humano 2010: Muito Alto &gt;= 0,9; Alto &gt;= 0,8; Médio &gt;= 0,5; Baixo &lt; 0,5.</td>
</tr>
<tr class="even">
<td>GE012</td>
<td>População Total Residente no Município</td>
</tr>
<tr class="odd">
<td>AG001</td>
<td>População Total Atendida com Abastecimento de Água</td>
</tr>
<tr class="even">
<td>AG020</td>
<td>Volume Micromedido nas Economias Residenciais Ativas de Agua - 1.000 m3/ano</td>
</tr>
<tr class="odd">
<td>AG022</td>
<td>Quantidade de Economias Residenciais Ativas Micromedidas</td>
</tr>
<tr class="even">
<td>CONSUMO1</td>
<td>Consumo de Água per capita - População Total - m3/ano (AG020/GE012)</td>
</tr>
<tr class="odd">
<td>CONSUMO2</td>
<td>Consumo de Água per capita - População Atendida - m3/ano (AG020/AG001)</td>
</tr>
</tbody>
</table>
<p>Além delas, estão presentes outras variáveis que trazem os resultados do modelo de regressão linear (.fitted, .resid, .std.resid, .hat, .sigma, .cooksd), conforme apresentado no <a href="https://luisfelipebr.github.io/mti2020/roteiros/roteiro5.html">Roteiro 5</a>.</p>
<p><strong>ATENÇÃO: Algumas considerações sobre os dados antes de rodar o modelo:</strong></p>
<ol type="1">
<li>O modelo não vai funcionar em uma base de dados com valores faltantes (NA).</li>
<li>É necessário trazer em uma coluna as coordenadas do centróide dos polígonos (longitude/latitude).</li>
<li>Os modelos de regressão espacial são complexos e exigem um tempo de processamento muito maior que os modelos lineares! Nos nossos testes, o tempo de processamento variou entre 10 a 30 minutos. Portanto, recomendamos rodar o modelo apenas em uma amostra dos dados (ex: <code>UF == "SP"</code>).</li>
</ol>
<p>As funções apresentadas nas aulas anteriores funcionam em dados geoespaciais de forma semelhante à tabelas. Vamos usá-las para resolver a primeira e segunda consideração.</p>
<p>Para filtrar apenas as observações completas, ou seja, sem valores faltantes (NA), podemos aplicar a função <code>drop_na()</code>, levando em consideração as variáveis que serão utilizadas (ID, Variável Y e Variável X), para remover as linhas que contém <code>NA</code> nas variáveis indicadas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>agua_rede_sf_sem_na <span class="ot">&lt;-</span> agua_rede_sf <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(ID_IBGE, CONSUMO1, RENDAPITA)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Dos 5567 municípios presentes na base de dados, apenas 4417 tinham informações completas do ID_IBGE, CONSUMO1 e RENDAPITA. O modelo será aplicado apenas nessas observações.</p>
<p><strong>Amostragem:</strong> o código abaixo cria uma amostra apenas com os dados do estado de São Paulo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>agua_rede_sf_sp <span class="ot">&lt;-</span> agua_rede_sf_sem_na <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(UF <span class="sc">==</span> <span class="st">"SP"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Para executar o modelo de regressão espacial local (GWR), é necessário ter variáveis que descrevem a longitude e latitude do centróide dos polígonos.</p>
<p>A função <code>st_centroid()</code> calcula o centróide de um polígono, porém ela só funciona se as geometrias forem consideradas “válidas”. Podemos fazer essa checagem com a função <code>st_is_valid()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Checando se a geometria é valida</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>geometrias_validas <span class="ot">&lt;-</span> <span class="fu">st_is_valid</span>(agua_rede_sf_sp)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Somando quantas geometrias são inválidas</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(geometrias_validas <span class="sc">==</span> <span class="cn">FALSE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>Agora podemos calcular o centróide:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>agua_rede_sf_sp_centroide <span class="ot">&lt;-</span> agua_rede_sf_sp <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">LON =</span> <span class="fu">st_coordinates</span>(<span class="fu">st_centroid</span>(agua_rede_sf_sp))[,<span class="dv">1</span>],</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">LAT =</span> <span class="fu">st_coordinates</span>(<span class="fu">st_centroid</span>(agua_rede_sf_sp))[,<span class="dv">2</span>])</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There were 2 warnings in `stopifnot()`.
The first warning was:
ℹ In argument: `LON = st_coordinates(st_centroid(agua_rede_sf_sp))[, 1]`.
Caused by warning:
! st_centroid assumes attributes are constant over geometries
ℹ Run `dplyr::last_dplyr_warnings()` to see the 1 remaining warning.</code></pre>
</div>
</div>
<p>Agora temos as colunas <code>LAT</code> e <code>LON</code>, mantendo a coluna <code>geom</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>agua_rede_sf_sp_centroide <span class="sc">|&gt;</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(LAT, LON, geom)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 510 features and 2 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -53.10986 ymin: -25.31232 xmax: -44.16137 ymax: -19.77966
Geodetic CRS:  SIRGAS 2000
# A tibble: 510 × 3
     LAT   LON                                                              geom
   &lt;dbl&gt; &lt;dbl&gt;                                                &lt;MULTIPOLYGON [°]&gt;
 1 -21.6 -51.1 (((-51.09093 -21.47214, -51.08788 -21.46944, -51.08722 -21.46444…
 2 -21.3 -49.7 (((-49.69668 -21.3443, -49.69703 -21.34019, -49.69894 -21.33772,…
 3 -21.9 -46.7 (((-46.73069 -21.9447, -46.73192 -21.93454, -46.73487 -21.9303, …
 4 -22.5 -46.6 (((-46.635 -22.45781, -46.62814 -22.45148, -46.62519 -22.44678, …
 5 -22.9 -49.3 (((-49.28903 -22.77028, -49.28139 -22.77217, -49.27747 -22.77183…
 6 -22.6 -47.9 (((-47.86292 -22.60939, -47.86517 -22.61207, -47.86423 -22.61583…
 7 -22.6 -49.1 (((-49.0167 -22.38629, -49.00953 -22.38424, -48.99643 -22.38395,…
 8 -23.5 -47.9 (((-47.86567 -23.51306, -47.86243 -23.50943, -47.85984 -23.51047…
 9 -21.9 -51.4 (((-51.37102 -21.87702, -51.36865 -21.87703, -51.36898 -21.87891…
10 -20.5 -49.1 (((-49.14974 -20.57783, -49.1535 -20.57674, -49.15553 -20.57754,…
# ℹ 500 more rows</code></pre>
</div>
</div>
</section>
<section id="modelos-de-regressão-espacial-global-spatial-lag-e-spatial-error" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="modelos-de-regressão-espacial-global-spatial-lag-e-spatial-error"><span class="header-section-number">8.5</span> Modelos de regressão espacial global (Spatial Lag e Spatial Error)</h2>
<p>Após a análise espacial dos resíduos - que permitiu observar que as observações não são independentes espacialmente, vamos incorportar a estrutura de dependência espacial no modelo.</p>
<p>Os modelos globais incluem no modelo de regressão um parâmetro para capturar a estrutura de autocorrelação espacial na área de estudo como um todo.</p>
<p>O Spatial Lag (SAR) atribue a autocorrelação espacial à variável resposta Y (lag), enquanto o Spatial Error (CAR) atribue a autocorrelação espacial ao erro.</p>
<section id="preparando-os-dados" class="level3" data-number="8.5.1">
<h3 data-number="8.5.1" class="anchored" data-anchor-id="preparando-os-dados"><span class="header-section-number">8.5.1</span> Preparando os dados</h3>
<p>O ponto de partida para o Spatial Lag e Spatial Error é o modelo de regressão linear (Roteiro 5), criado com a função <code>lm()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>modelo1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> CONSUMO1 <span class="sc">~</span> RENDAPITA, </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> agua_rede_sf_sp_centroide, </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">na.action =</span> na.exclude)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Também é necessário criar um arquivo com a lista de vizinhança, com a função <code>poly2nb()</code>. Foi usado o critério de vizinhança do tipo <code>queen</code>. Para usar outros critérios, lembre-se de consultar a documentação da função.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>vizinhanca <span class="ot">&lt;-</span> <span class="fu">poly2nb</span>(<span class="at">pl =</span> agua_rede_sf_sp_centroide, </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">row.names =</span> agua_rede_sf_sp_centroide<span class="sc">$</span>ID_IBGE)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in poly2nb(pl = agua_rede_sf_sp_centroide, row.names = agua_rede_sf_sp_centroide$ID_IBGE): some observations have no neighbours;
if this seems unexpected, try increasing the snap argument.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in poly2nb(pl = agua_rede_sf_sp_centroide, row.names = agua_rede_sf_sp_centroide$ID_IBGE): neighbour object has 5 sub-graphs;
if this sub-graph count seems unexpected, try increasing the snap argument.</code></pre>
</div>
</div>
<p>Visualizando o sumário desse arquivo, é possível ter uma ideia da distribuição da vizinhança.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(vizinhanca)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 510 
Number of nonzero links: 2290 
Percentage nonzero weights: 0.8804306 
Average number of links: 4.490196 
3 regions with no links:
3520400, 3543204, 3546702
5 disjoint connected subgraphs
Link number distribution:

  0   1   2   3   4   5   6   7   8   9  10  11  20 
  3  15  50 103 114  82  75  34  15   9   8   1   1 
15 least connected regions:
3500402 3500600 3501400 3503158 3504701 3504909 3508702 3523701 3527108 3534302 3534708 3539905 3546108 3546207 3551900 with 1 link
1 most connected region:
3550308 with 20 links</code></pre>
</div>
</div>
<p>Agora é possível criar uma matriz de pesos espaciais, com as funções <code>nb2mat()</code> e <code>mat2listw()</code>. Em vários momentos é necessário definir o argumento adicional <code>zero.policy = TRUE</code>, que permite obter os resultados mesmo que uma ou mais observações não tenham nenhum vizinho. Não se esqueça de adicionar este parâmetro sempre que indicado neste roteiro.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>wm <span class="ot">&lt;-</span> <span class="fu">nb2mat</span>(<span class="at">neighbours =</span> vizinhanca, <span class="at">style=</span><span class="st">'B'</span>, <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>rwm <span class="ot">&lt;-</span> <span class="fu">mat2listw</span>(<span class="at">x =</span> wm, <span class="at">style=</span><span class="st">'W'</span>, <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in mat2listw(x = wm, style = "W", zero.policy = TRUE): neighbour object
has 5 sub-graphs</code></pre>
</div>
</div>
<p>Agora já é possível realizar o teste de autocorrelação espacial dos resíduos, com a função <code>lm.morantest()</code>, que levará como argumentos: o modelo (modelo1), a matriz de pesos espaciais (rwm) e a tipo de hipótese alternativa (“two-sided”, que representa o teste bicaudal).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm.morantest</span>(<span class="at">model =</span> modelo1, </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">listw =</span> rwm, </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Global Moran I for regression residuals

data:  
model: lm(formula = CONSUMO1 ~ RENDAPITA, data =
agua_rede_sf_sp_centroide, na.action = na.exclude)
weights: rwm

Moran I statistic standard deviate = 9.5448, p-value &lt; 2.2e-16
alternative hypothesis: two.sided
sample estimates:
Observed Moran I      Expectation         Variance 
     0.297470015     -0.002570733      0.000988155 </code></pre>
</div>
</div>
<p>O resultado do teste é significativo (p-valor &lt; 0,00000000000000022), portanto há dependência espacial nos resíduos e um modelo de regressão espacial global pode ser aplicado.</p>
<p>Mas antes disso serão aplicados quatro testes de hipótese para identificar qual é o modelo mais adequado (Spatial Lag ou Spatial Error):</p>
<ul>
<li>LMerr: teste LM simples para dependência do erro</li>
<li>LMlag: teste LM simples para uma variável dependente espacialmente defasada</li>
<li>RLMerr: teste LM robusto para dependência do erro</li>
<li>RLMlag: teste LM robusto para uma variável dependente espacialmente defasada</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm.LMtests</span>(<span class="at">model =</span> modelo1,</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">listw =</span> rwm,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">test =</span> <span class="fu">c</span>(<span class="st">"LMerr"</span>,<span class="st">"LMlag"</span>,<span class="st">"RLMerr"</span>,<span class="st">"RLMlag"</span>),</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Please update scripts to use lm.RStests in place of lm.LMtests</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Rao's score (a.k.a Lagrange multiplier) diagnostics for spatial
    dependence

data:  
model: lm(formula = CONSUMO1 ~ RENDAPITA, data =
agua_rede_sf_sp_centroide, na.action = na.exclude)
test weights: listw

RSerr = 89.586, df = 1, p-value &lt; 2.2e-16


    Rao's score (a.k.a Lagrange multiplier) diagnostics for spatial
    dependence

data:  
model: lm(formula = CONSUMO1 ~ RENDAPITA, data =
agua_rede_sf_sp_centroide, na.action = na.exclude)
test weights: listw

RSlag = 72.74, df = 1, p-value &lt; 2.2e-16


    Rao's score (a.k.a Lagrange multiplier) diagnostics for spatial
    dependence

data:  
model: lm(formula = CONSUMO1 ~ RENDAPITA, data =
agua_rede_sf_sp_centroide, na.action = na.exclude)
test weights: listw

adjRSerr = 17.354, df = 1, p-value = 3.102e-05


    Rao's score (a.k.a Lagrange multiplier) diagnostics for spatial
    dependence

data:  
model: lm(formula = CONSUMO1 ~ RENDAPITA, data =
agua_rede_sf_sp_centroide, na.action = na.exclude)
test weights: listw

adjRSlag = 0.50775, df = 1, p-value = 0.4761</code></pre>
</div>
</div>
<p>Como interpretar os resultados dos testes de hipótese dos multiplicadores de Lagrange?</p>
<p>Primeiro examinamos os testes simples (LMerr e LMlag). Se eles não forem significativos (p-valor &gt; 0,05), a hipótese de modelagem do erro ou lag não se sustenta. Se apenas um deles for significativo (p-valor &lt; 0,05): problema resolvido - mas é bastante comum que ambos sejam significativos. Se ambos forem significativos, é necessário conferir os testes robustos.</p>
<p>Olhando para os multiplicadores de Lagrange robustos (RLMlag e RLMerr), normalmente, apenas um deles será significativo, ou um terá uma ordem de magnitude mais significativo do que o outro (por exemplo, p &lt; 0,000003 em comparação com p &lt; 0,03). Nesse caso, a decisão é simples: estimar o modelo de regressão espacial correspondendo à estatística mais “robusta” (ou significativa). No caso raro de ambos serem altamente significativos, escolha o modelo com o maior valor para a estatística de teste. No entanto, nesta situação, é necessário algum cuidado, uma vez que podem existir outras fontes de erros de especificação. Outra ação a se tomar é alterar a especificação básica (ou seja, a parte não espacial) do modelo.</p>
<p>Também há casos raros em que nenhuma das estatísticas do teste robusto é significativa. Nesses casos, problemas de especificação mais sérios provavelmente estão presentes e devem ser resolvidos primeiro. Por outros erros de especificação, nos referimos a problemas com algumas das outras suposições da regressão linear (Roteiro 5).</p>
<p>Neste caso, os dois testes simples são significativos. Mas o teste de erro robusto é mais significativo que o teste de lag robusto, então o modelo mais apropriado seria o Spatial Error (CAR). De qualquer forma, vamos ensinar a aplicar os dois modelos (SAR e CAR) na sequência.</p>
</section>
<section id="spatial-autoregressive-model-spatial-lagsar" class="level3" data-number="8.5.2">
<h3 data-number="8.5.2" class="anchored" data-anchor-id="spatial-autoregressive-model-spatial-lagsar"><span class="header-section-number">8.5.2</span> Spatial Autoregressive Model (Spatial Lag/SAR)</h3>
<p>Para aplicar o modelo Spatial Lag usaremos a função <code>lagsarlm()</code>, especificando a fórmula, os dados e a matriz de pesos espaciais.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>sar_modelo <span class="ot">&lt;-</span> <span class="fu">lagsarlm</span>(<span class="at">formula =</span> CONSUMO1 <span class="sc">~</span> RENDAPITA,</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">data =</span> agua_rede_sf_sp_centroide,</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">listw =</span> rwm,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Para ver os resultados do novo modelo, você pode acessar o sumário.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sar_modelo)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lagsarlm(formula = CONSUMO1 ~ RENDAPITA, data = agua_rede_sf_sp_centroide, 
    listw = rwm, zero.policy = TRUE)

Residuals:
     Min       1Q   Median       3Q      Max 
-51.5374  -6.2923  -1.1463   3.5627 128.1935 

Type: lag 
Regions with no neighbours included:
 3520400 3543204 3546702 
Coefficients: (asymptotic standard errors) 
             Estimate Std. Error z value  Pr(&gt;|z|)
(Intercept) 7.5769500  2.7147528   2.791  0.005254
RENDAPITA   0.0316423  0.0030092  10.515 &lt; 2.2e-16

Rho: 0.35367, LR test value: 60.126, p-value: 8.8818e-15
Asymptotic standard error: 0.045679
    z-value: 7.7426, p-value: 9.77e-15
Wald statistic: 59.948, p-value: 9.77e-15

Log likelihood: -2061.04 for lag model
ML residual variance (sigma squared): 183.69, (sigma: 13.553)
Number of observations: 510 
Number of parameters estimated: 4 
AIC: 4130.1, (AIC for lm: 4188.2)
LM test for residual autocorrelation
test value: 1.9034, p-value: 0.1677</code></pre>
</div>
</div>
<p>O modelo SAR possui um melhor desempenho que o modelo de regressão linear, indicado pelo AIC (4130), que é menor que o AIC do modelo de regressão linear (4188). Além disso, o teste de autocorrelação espacial dos resíduos não é significativo (p-valor = 0,16), indicando que após a modelagem os resíduos não são mais correlacionados espacialmente.</p>
</section>
<section id="conditional-autoregressive-model-spatial-errorcar" class="level3" data-number="8.5.3">
<h3 data-number="8.5.3" class="anchored" data-anchor-id="conditional-autoregressive-model-spatial-errorcar"><span class="header-section-number">8.5.3</span> Conditional Autoregressive Model (Spatial Error/CAR)</h3>
<p>Para aplicar o modelo Spatial Error usaremos a função <code>errorsarlm()</code>, especificando a fórmula, os dados e a matriz de pesos espaciais.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>car_modelo <span class="ot">&lt;-</span> <span class="fu">errorsarlm</span>(<span class="at">formula =</span> CONSUMO1 <span class="sc">~</span> RENDAPITA,</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> agua_rede_sf_sp_centroide,</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">listw =</span> rwm,</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>É possível visualizar os resultados do modelo usando o sumário.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(car_modelo)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
errorsarlm(formula = CONSUMO1 ~ RENDAPITA, data = agua_rede_sf_sp_centroide, 
    listw = rwm, zero.policy = TRUE)

Residuals:
     Min       1Q   Median       3Q      Max 
-49.3458  -6.4307  -1.1948   3.6627 126.9162 

Type: error 
Regions with no neighbours included:
 3520400 3543204 3546702 
Coefficients: (asymptotic standard errors) 
              Estimate Std. Error z value  Pr(&gt;|z|)
(Intercept) 22.5150675  2.4084788  9.3483 &lt; 2.2e-16
RENDAPITA    0.0341102  0.0031534 10.8170 &lt; 2.2e-16

Lambda: 0.42026, LR test value: 69.624, p-value: &lt; 2.22e-16
Asymptotic standard error: 0.049799
    z-value: 8.4391, p-value: &lt; 2.22e-16
Wald statistic: 71.218, p-value: &lt; 2.22e-16

Log likelihood: -2056.291 for error model
ML residual variance (sigma squared): 177.77, (sigma: 13.333)
Number of observations: 510 
Number of parameters estimated: 4 
AIC: 4120.6, (AIC for lm: 4188.2)</code></pre>
</div>
</div>
<p>O AIC do modelo CAR (4120) é menor que o AIC do modelo de regressão linear (4188), indicando um melhor resultado. Além disso, todos os valores estimados são significativos (p-valor &lt; 0,05).</p>
</section>
<section id="exportando-os-resíduos-do-modelo" class="level3" data-number="8.5.4">
<h3 data-number="8.5.4" class="anchored" data-anchor-id="exportando-os-resíduos-do-modelo"><span class="header-section-number">8.5.4</span> Exportando os resíduos do modelo</h3>
<p>Para verificar a autocorrelação espacial no GeoDa, é necessário exportar os resíduos do modelo. O código abaixo indica como executar essa etapa para os dois modelos, criando as variáveis (colunas) sar_residuos e car_residuos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>agua_rede_sar_car <span class="ot">&lt;-</span> agua_rede_sf_sp_centroide <span class="sc">|&gt;</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sar_residuos =</span> <span class="fu">residuals</span>(sar_modelo),</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">car_residuos =</span> <span class="fu">residuals</span>(car_modelo))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Após criar essa nova base de dados, você pode exportá-la como geopackage ou shapefile com a função <code>write_sf()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_sf</span>(agua_rede_sar_car, <span class="st">"dados/agua_rede_sar_car.gpkg"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_sf</span>(agua_rede_sar_car, <span class="st">"dados/agua_rede_sar_car.shp"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="modelo-de-regressão-espacial-local-gwr" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="modelo-de-regressão-espacial-local-gwr"><span class="header-section-number">8.6</span> Modelo de regressão espacial local (GWR)</h2>
<p>O modelo de regressão espacial local ou Geographically Weighted Regression (GWR) incorpora a estrutura de dependência espacial (verificada com o teste de autocorrelação espacial - Roteiro 6).</p>
<p>Nesse modelo, as variações espaciais são modeladas de forma contínua, com parâmetros variando no espaço. Ele ajusta um modelo de regressão para cada observação, ponderando todas as demais observações como função da distância a este ponto. Existe uma função (kernel) sobre cada ponto do espaço que determina todos os pontos da regressão local que é ponderada pela distância. Pontos mais próximos do ponto central tem maior peso. Assim como no kernel, a escolha da largura da banda é importante, pondendo ser fixa ou adaptável à densidade dos dados.</p>
<p>O processo de modelagem envolverá quatro etapas: (1) estimativa do kernel, (2) cômputo do modelo, (3) análise do sumário do modelo e (4) exportação dos resultados para análise espacial no QGIS.</p>
<p>É possível obter a melhor estimativa do kernel com a função <code>gwr.sel()</code>. Como argumentos, indicamos a fórmula, os dados, as coordenadas dos centróides e indicamos que a largura da banda será adaptativa (<code>adapt = TRUE</code>). O resultado será salvo no objeto <code>gwr_kernel</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>gwr_kernel <span class="ot">&lt;-</span> <span class="fu">gwr.sel</span>(<span class="at">formula =</span> CONSUMO1 <span class="sc">~</span> RENDAPITA, </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> agua_rede_sf_sp_centroide,</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">coords =</span> <span class="fu">cbind</span>(agua_rede_sf_sp_centroide<span class="sc">$</span>LON,</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>                                       agua_rede_sf_sp_centroide<span class="sc">$</span>LAT),</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>                        <span class="at">adapt =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Adaptive q: 0.381966 CV score: 102015.2 
Adaptive q: 0.618034 CV score: 105439.5 
Adaptive q: 0.236068 CV score: 98555.9 
Adaptive q: 0.145898 CV score: 95869.4 
Adaptive q: 0.09016994 CV score: 93855.01 
Adaptive q: 0.05572809 CV score: 92954.56 
Adaptive q: 0.03444185 CV score: 92782.26 
Adaptive q: 0.03259011 CV score: 92883.41 
Adaptive q: 0.04359183 CV score: 92738.4 
Adaptive q: 0.04822747 CV score: 92801.64 
Adaptive q: 0.04080911 CV score: 92746.26 
Adaptive q: 0.04536248 CV score: 92721.9 
Adaptive q: 0.04645681 CV score: 92737.45 
Adaptive q: 0.04504466 CV score: 92718.97 
Adaptive q: 0.04448972 CV score: 92726.54 
Adaptive q: 0.04500397 CV score: 92719.53 
Adaptive q: 0.0451316 CV score: 92718.7 
Adaptive q: 0.04521979 CV score: 92719.92 
Adaptive q: 0.0451723 CV score: 92719.26 
Adaptive q: 0.04509091 CV score: 92718.33 
Adaptive q: 0.04509091 CV score: 92718.33 </code></pre>
</div>
</div>
<p>Após obter a melhor estimativa para o kernel, é possível fazer a modelagem com a função <code>gwr()</code>. Além da fórmula, dados e coordenadas, é necessário indicar o kernel (<code>adapt = gwr_kernel</code>) e dois argumentos adicionais para salvar os resultados completos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>gwr_modelo <span class="ot">&lt;-</span> <span class="fu">gwr</span>(<span class="at">formula =</span> CONSUMO1 <span class="sc">~</span> RENDAPITA,</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> agua_rede_sf_sp_centroide,</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">coords =</span> <span class="fu">cbind</span>(agua_rede_sf_sp_centroide<span class="sc">$</span>LON,</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>                               agua_rede_sf_sp_centroide<span class="sc">$</span>LAT),</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">adapt =</span> gwr_kernel, </span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">hatmatrix =</span> <span class="cn">TRUE</span>,</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>É possível visualizar o sumário com alguns resultados executando como comando o nome do objeto onde o modelo foi salvo, <code>gwr_modelo</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>gwr_modelo</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
gwr(formula = CONSUMO1 ~ RENDAPITA, data = agua_rede_sf_sp_centroide, 
    coords = cbind(agua_rede_sf_sp_centroide$LON, agua_rede_sf_sp_centroide$LAT), 
    adapt = gwr_kernel, hatmatrix = TRUE, se.fit = TRUE)
Kernel function: gwr.Gauss 
Adaptive quantile: 0.04509091 (about 22 of 510 data points)
Summary of GWR coefficient estimates at data points:
                  Min.   1st Qu.    Median   3rd Qu.      Max.  Global
X.Intercept.  3.193279 16.736881 21.030497 26.436066 37.206325 20.5236
RENDAPITA     0.020480  0.029492  0.035011  0.041511  0.057511  0.0369
Number of data points: 510 
Effective number of parameters (residual: 2traceS - traceS'S): 32.04562 
Effective degrees of freedom (residual: 2traceS - traceS'S): 477.9544 
Sigma (residual: 2traceS - traceS'S): 13.39139 
Effective number of parameters (model: traceS): 22.38185 
Effective degrees of freedom (model: traceS): 487.6182 
Sigma (model: traceS): 13.25803 
Sigma (ML): 12.96385 
AICc (GWR p. 61, eq 2.33; p. 96, eq. 4.21): 4109.837 
AIC (GWR p. 96, eq. 4.22): 4083.107 
Residual sum of squares: 85711.26 
Quasi-global R2: 0.3793284 </code></pre>
</div>
</div>
<p>Duas estatísticas muito importantes sobre o modelo são o AIC e o R². Neste caso o AIC do modelo de regressão espacial local (4083) é menor que o AIC do modelo de regressão linear (4188), indicando um melhor resultado. O R² “quasi-global” (0,37) é maior que o R² do modelo de regressão linear (0,21), também indicando um melhor resultado.</p>
<p>Também é importante verificar os parâmetros locais estimados e o coeficiente local de determinação (R²). Para visualizar esses parâmetros, vamos exportar uma nova base de dados (em formato geopackage ou shapefile) para abrir e visualizar no QGIS.</p>
<p>O código abaixo indica como executar essa última etapa.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>agua_rede_gwr <span class="ot">&lt;-</span> <span class="fu">cbind</span>(agua_rede_sf_sp_centroide,</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>                       <span class="fu">as.matrix</span>(<span class="fu">as.data.frame</span>(gwr_modelo<span class="sc">$</span>SDF))) <span class="sc">|&gt;</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">t_beta1 =</span> RENDAPITA<span class="fl">.1</span> <span class="sc">/</span> RENDAPITA_se)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As novas variáveis são:</p>
<ul>
<li><code>X.Intercept</code> = valores locais de beta zero (intercepto)</li>
<li><code>RENDAPITA.1</code> = valores locais do coeficiente de renda per capita (X1)</li>
<li><code>X.Intercept_se</code> = erro padrão de beta zero (intercepto)</li>
<li><code>RENDAPITA_se</code> = erro padrão do coeficiente estimado para renda per capita (X1)</li>
<li><code>t_beta1</code> = estatística t local para o coeficiente de renda per capita</li>
<li><code>pred</code> = valores previstos de Y</li>
<li><code>localR2</code> = valores locais de R2</li>
</ul>
<p>Para interpretar os resultados do GWR, é importante mapear algumas estatísticas, tais como o R2 local, os coeficientes beta e estatísticas t.</p>
<p>Para obter a estatística t para cada coeficiente beta, deve-se dividir os valores dos coeficientes (por exemplo, RENDAPITA.1) por seus respectivos erros padrão (RENDAPITA_se). Se o módulo da estatística t for maior do que o valor do t crítico, pode-se rejeitar a hipótese nula de que beta é igual a zero (ou seja, beta é significativo).</p>
<p>A variável “pred” apresenta os parâmetros locais estimados para a variável Renda per capita, enquanto a variável “localR2” apresenta o coeficiente local de determinação (R²). Também é interessante aplicar um teste de autocorrelação espacial nos resíduos, para verificar se a dependência espacial foi resolvida pelo modelo.</p>
<p>Para exportar como geopackage:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_sf</span>(agua_rede_gwr, <span class="st">"dados/agua_rede_gwr.gpkg"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Para exportar como shapefile:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_sf</span>(agua_rede_gwr, <span class="st">"dados/agua_rede_gwr.shp"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="sugestões-de-materiais" class="level2" data-number="8.7">
<h2 data-number="8.7" class="anchored" data-anchor-id="sugestões-de-materiais"><span class="header-section-number">8.7</span> Sugestões de materiais</h2>
<ul>
<li><a href="https://ipeadata-lab.github.io/curso_r_intermediario_202501/dados-espaciais.html">Dados espaciais no R</a> - material do curso “R intermediário e pesquisa reprodutível”</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/beatrizmilz\.github\.io\/ESHT011-21-analise-dados-planejamento-territorial\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../praticas/07_regressao-linear.html" class="pagination-link" aria-label="Regressão Linear">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Regressão Linear</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../apendices/00_erros_frequentes.html" class="pagination-link" aria-label="Erros e *warnings* frequentes">
        <span class="nav-page-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Erros e <em>warnings</em> frequentes</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/beatrizmilz/ESHT011-21-analise-dados-planejamento-territorial/edit/main/praticas/08_regressao-espacial.qmd" class="toc-action"><i class="bi bi-github"></i>Editar essa página</a></li><li><a href="https://github.com/beatrizmilz/ESHT011-21-analise-dados-planejamento-territorial/issues/new" class="toc-action"><i class="bi empty"></i>Criar uma issue</a></li><li><a href="https://github.com/beatrizmilz/ESHT011-21-analise-dados-planejamento-territorial/blob/main/praticas/08_regressao-espacial.qmd" class="toc-action"><i class="bi empty"></i>Ver o código fonte</a></li></ul></div></div></div></footer></body></html>