project:
  type: book
  output-dir: docs

execute:
  freeze: auto
  
lang: pt 
language:
  title-block-author-single: "Docente"
  title-block-author-plural: "Docentes" 
  title-block-published: "Atualizado em"

book:
  title: "Análise de dados para o Planejamento Territorial"
  subtitle: "ESHT011-21 - 2025"
  site-url: "https://beatrizmilz.github.io/ESHT011-21-analise-dados-planejamento-territorial/"
  repo-url: "https://github.com/beatrizmilz/ESHT011-21-analise-dados-planejamento-territorial"  
  date: "6/2/2025"
  repo-branch: main
  repo-actions: [edit, issue]  
  chapters:
    - index.qmd
    - praticas/01_intro_r_rstudio.qmd
    - praticas/02_conceitos-basicos-r.qmd    
    # - praticas/02_analise-exploratoria_i.qmd
    # - praticas/03_analise-exploratoria_ii.qmd    
    # - praticas/04_correlacao.qmd
    # - praticas/06_regressao-linear.qmd    
    # - praticas/07_regressao-espacial.qmd        
    # 

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    code-link: true
  # pdf:
  #   documentclass: scrreprt

editor: visual

author:
  - name: "Flávia da Fonseca Feitosa"
    url: "https://sig.ufabc.edu.br/sigaa/public/docente/portal.jsf?siape=2064223"
    email: "flavia.feitosa@ufabc.edu.br"
  - name: "Beatriz Milz"
    url: "https://www.beamilz.com/"
    email: "milz.bea@gmail.com"