project:
  type: book
  output-dir: docs

execute:
  freeze: auto
  
lang: pt 
language:
  title-block-author-single: "Docente"
  title-block-author-plural: "Docentes" 
  title-block-published: "Atualizado em"

book:
  title: "Análise de dados para o Planejamento Territorial"
  subtitle: "Práticas em R"
  site-url: "https://beatrizmilz.github.io/ESHT011-21-analise-dados-planejamento-territorial/"
  repo-url: "https://github.com/beatrizmilz/ESHT011-21-analise-dados-planejamento-territorial"  
  date: last-modified
  repo-branch: main
  repo-actions: [edit, issue, source]  
  downloads: [pdf]
  output-file: "analise-de-dados-para-planejamento-territorial"
  chapters:
    - index.qmd
    - praticas/01_intro_r_rstudio.qmd
    - praticas/02_conceitos-basicos-r.qmd    
    - praticas/03_analise-exploratoria.qmd
    - praticas/04_analise-exploratoria-ii.qmd
    - praticas/05_intervalo-de-confianca.qmd
    - praticas/06_correlacao.qmd
    - praticas/07_regressao-linear.qmd    
    - praticas/08_regressao-espacial.qmd           
  appendices:
    - apendices/00_erros_frequentes.qmd    
    - apendices/00_sugestao-videos.qmd        
     

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
 #     - brand
    code-link: true
  pdf:
    documentclass: scrreprt
   # mainfont: Verdana

editor: visual

author:
  - name: "Flávia da Fonseca Feitosa"
    url: "https://sig.ufabc.edu.br/sigaa/public/docente/portal.jsf?siape=2064223"
    email: "flavia.feitosa@ufabc.edu.br"
  - name: "Beatriz Milz"
    url: "https://www.beamilz.com/"
    email: "milz.bea@gmail.com"